README.md
This PR adds a build status indicator to the README file. It is not a substantial change, but I always like it when a project has some (meaningful) badges in its README.
=> chore: add CI status and license badges to README file

.github/workflows/build.yml
Since our Ubuntu workflow is much faster than the macOS one (due to the pre-build CI image), we can let the macOS workflow run only after Ubuntu workflow has succeeded. This lets the CI fail fast if there should be some kind of error and saves us some (more restricted) macOS run time.
=> chore(ci): run macOS build only after Ubuntu build succeeded

.github/workflows/build.yml, .gitignore, .gitlab-ci.yml, CMakeLists.txt, README.md, tests/CMakeLists.txt, tests/iceflow_test.cpp
This PR adds the foundation for a basic testing workflow based on CMake's CTest. In follow-up PRs, this foundation can be extended to use a testing framework like Boost.Test or Google Test.
=> test: set up basic test framework

README.md
This PR adds the correct link the to rendered Doxygen documentation as well as a status badge to the README file.
=> docs: add documentation link and badge to README

.dockerignore, .github/workflows/docker-image.yml, Dockerfile
This PR adds a GitHub Actions workflow that builds a Docker image containing both the NFD and our IceFlow applications. The images built should be compatible with the architecture our Raspberry Pis are using (armv7, if I am not mistaken), which could simplify the Deployment here.
This approach has to be considered somewhat experimental (especially when considering the question of whether or not the images will be usable with an Ethernet face), but I thought it would be useful to have this kind of infrastructure in place.
=> feat: create Docker workflow

include/iceflow/block.hpp, include/iceflow/typed-data.hpp
Having another look at the source code, I noticed that the `membuf` class is not actually being used and can simply be removed, which cleans up the codebase a bit more.
=> refactor: remove membuf class

.github/workflows/build.yml, CMakeLists.txt, README.md, cmake/formatting.cmake
This PR simplifies the process of using clang-format for formatting the codebase using custom CMake build targets. The README as well as the CI workflows are updated accordingly.
=> chore: integrate clang-format into CMake build process

.github/workflows/docker-image.yml
Using the `concurrency` keyword, this PR adjusts the CI behavior to only build one Docker image per branch at a time, canceling previous runs. This prevents the CI from wasting time building outdated images.
=> chore(ci): run only one Docker image workflow at a time

include/iceflow/data.hpp
This is another cleanup PR, removing some unused elements from the `Data` class (as pointed out by cppcheck).
=> refactor: remove unused methods and fields from Data class

include/iceflow/consumer-tlv.hpp
This PR applies some refactoring to the `ConsumerTlv` class, moving the filtering of NDN names of `ndn::Data` objects to a separate method. This also gets rid of a complaint by cppcheck regarding the for loop that was being used before.
=> refactor(consumer-tlv): refactor manifest name filtering

README.md
This PR reorganizes the README file a bit in order to reduce redundancy by creating a separate section to document the generation of build files using CMake.
=> docs(README): factor build files generation into its own section

Install.md
In order to make the installation instructions more generic/universal, this PR replaces most of the system-specific instructions with links to the instructions given by our dependencies (such as ndn-cxx), where possible. The PR also adds instructions for actually installing IceFlow (using `sudo make install`).
I also just noticed that the opencv dependency is not yet listed, so that should either be added to this PR or a follow-up one.
=> docs: rework installation instructions

README.md
For some reason, the minimum CMake version in the README file remained unchanged. This PR adjusts the version mentioned in the file from 3.21 to 3.18 (as done before in #28).
=> docs: adjust minimum CMake version in README

.github/workflows/docker-image.yml, Dockerfile
This should speed up the build time of the Docker image dramatically, as the CI is now not rebuilding the NFD every time but instead re-uses the CI image.
=> refactor: use CI image as basis for IceFlow Docker image

apps/AgeDetection/agedetection.cpp, apps/Aggregate/aggregate.cpp, apps/CMakeLists.txt, apps/FaceDetection/facedetection.cpp, apps/GenderDetection/genderdetection.cpp, apps/ImageSource/imagesource.cpp, apps/PeopleCounter/peoplecounter.cpp, apps/include/util.hpp, apps/util/util.cpp, cmake/format.cmake, include/iceflow/block.hpp
This PR resolves #24 by moving the OpenCV-specific helper functions to `util` files specific to the currently defined `apps`.
=> refactor!: move apps specific functions to util files

Dockerfile
This PR lets the Dockerfile invoke `make install`, making it possible to use IceFlow as a library in other inheriting Docker images.
=> feat: install IceFlow as library in Docker image

apps/FaceDetection/facedetection.cpp, apps/PeopleCounter/peoplecounter.cpp, include/iceflow/consumer-tlv.hpp
As it is more common to use the post-increment operator (`i++`) instead of the pre-increment operator (`++i`) in for-loop-statements and as both have the exact same effect in that context, this PR makes corresponding replacements to reduce the potential for confusion in the codebase.
=> refactor: use post-increment instead of pre-increment in for-loops

.github/workflows/build.yml
As I noticed that there is a APT repository with nightly builds of NDN packages for a number of Debian-based Linux distributions created by yoursunny, this PR incorporates an installation of `ndn-cxx` and `libpsync` from this repository into the CI.
Since the build on Ubuntu now takes a bit longer, I removed it as a dependency of the macOS job to make up for the lost time. Since the build on Ubuntu should fail early in case of any issues and thus cancel the whole workflow run, removing the dependency should be fine.
Lastly, as the repository also includes packages for Raspberry Pi, we should be able to integrate them into our test setup there.
=> ci: install ndn-cxx and libpsync on Ubuntu from APT repository

Doxyfile
Should fix #48 by explicitly pointing to the top-level `README.md` file in the `Doxyfile` for the documentation main page.
=> docs: use top-level README.md for Doxygen index.html

.linter-suppressions, cmake/lint.cmake
This PR adds two suppression rules (`missingIncludeSystem` and `unusedFunction`) for `cppcheck` in order to make using the linting step a bit more useful. As `make lint` probably won't report false positives anymore, we could consider letting the linting CI step fail (after fixing the remaining minor issues) if there are any warnings emitted.
=> chore: define suppression rules for cppcheck

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/text2lines/text2lines.cpp, examples/wordCount/wordcount/wordcount.cpp, flake.lock, include/CMakeLists.txt, include/iceflow/consumer.hpp, include/iceflow/iceflow.hpp, include/iceflow/producer.hpp
This PR introduces three subclasses to fulfill the roles of consumer, producer, and a combined consumer/producer ("prosumer"). They inherit from the common `IceFlow` base class, which is turned abstract now in the sense that both its constructor and the methods for pushing and receiving data are now labelled as protected.
I think the general concept should point into the right direction, however, we might need to discuss the details a bit more when we meet the next time. After we resolved this discussion, we can think about a more dynamic way of subscribing and publishing to topics, as well as an API to modify the number of partitions at runtime.
=> feat!: rework consumer and producer creation

include/iceflow/producer.hpp
When running an `IceflowProducer`, it might be desirable to be able to configure its `publishInterval` at runtime. This PR adds a corresponding setter as well as a check to the constructor to ensure that the time value that is being passed is always positive.
=> feat(producer.hpp): make `publishInterval` configurable at runtime

include/iceflow/producer.hpp
Just noticed that there is doubled closing namespace comment in file of the producer class. This PR applies a simple fix for that.
=> chore: remove obsolete namespace comment

include/iceflow/consumer.hpp, include/iceflow/producer.hpp
This PR applies changes similar to #54 to both the consumer and the producer class, only with regard to the `topicPartitions`. In this case, both the setter and the constructor perform a check to ensure that the partition vector is not empty.
There is currently some code duplication present which is not really desirable, I wasn't entirely sure about the best approach to avoid it at the moment. I suppose we could move the method that performs the check to a `util.hpp` or even the `iceflow.hpp` file – do you think that would make sense here, or is the amount of duplication tolerable?
=> feat: make `topicPartitions` configurable at runtime

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/text2lines/text2lines.cpp, examples/wordCount/wordcount/wordcount.cpp, include/iceflow/consumer.hpp, include/iceflow/iceflow.hpp, include/iceflow/producer.hpp
In the context of #56, I got the impression that it doesn't really make sense to use `int` as a datatype for the partition numbers as they should probably always be positive. Therefore, this PR proposes changing the datatype to `uint64_t`, which also aligns it with the datatype used by `ndn-cxx` for creating/appending numeric name components (via the `appendNumber`method).
As a next step (in a follow-up PR), I would change the data structure used for the partition numbers from an `std::vector` to an `std::unordered_set` in order to ensure that a partition number cannot be used twice.
=> feat!: use `uint64_t` instead of `int` for partition numbers

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/lines2words/lines2words1.yaml, examples/wordCount/lines2words/lines2words2.yaml, examples/wordCount/text2lines/text2lines.cpp, examples/wordCount/text2lines/text2lines.yaml, examples/wordCount/wordcount/wordcount.cpp, examples/wordCount/wordcount/wordcount.yaml, include/iceflow/measurements.hpp
This PR adds another round of smaller changes to improve the quality of the code and to make some parts of the code more understandable.
The most significant change is actually the renaming of the parameter `saveInterval` to `saveThreshold` to make it a bit clearer that this is not a time interval, but a threshold related to the number of measurement entries. Furthermore, similar to #60, the parameter is now being parsed as a `uint64_t`, enforcing a positive threshold.
In general, this area of the codebase requires some more work and better documentation. Also, some columns of the CSV files are not really being used at the moment (in particular, `interest` and `dataSize`) so we might need to discuss what we actually want to measure with this class and whether it should be part of the core …
=> fix: improve handling of measurements

.github/workflows/build.yml
I've noticed that the CI workflow currently still tries to upload build artifacts that are not created anymore. Therefore, this PR removes the corresponding lines from the `build.yaml` file.
We could, however, also consider exporting the new generated binaries, but I guess that does not have that much value considering that we have the docker images.
=> ci: remove build artifact upload steps

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/text2lines/text2lines.cpp, include/iceflow/producer.hpp
This PR adds a couple of additional small changes regarding the handling of the `publishInterval`, enforcing positive values already for the config files. In the `IceflowProducer` class itself, the check for positive values is slightly refactored.
=> fix: better enforce positive publish intervals 

Dockerfile
This PR removes the now obsolete `Dockerfile`, which has been become unnecessary after the switch to the new Nix-based approach (see #51).
=> chore: remove Dockerfile

cmake/lint.cmake, examples/wordCount/wordcount/wordcount.cpp
This PR makes the linting step in the CI a bit stricter by letting `cppcheck` exit with an error code if a warning is emitted.
To let the CI actually pass, this PR also address the one warning that was still emitted by the linter regarding the use of loop instead of a transform algorithm for converting the words in the `wordCount` example to lowercase.
=> chore: let lint target fail on warning

include/iceflow/iceflow.hpp
This PR resolves one source TODO comment in the source code by getting rid of the helper variable `timepointSet` by introducing an `std::optional` instead.
=> Fix and improve behavior of publication loop

doc/Nix-Developer-Guide.md
Hello there 👋!
The NixOS wiki is in the process of migrating from https://nixos.wiki to https://wiki.nixos.org.
You can find more information about it [here](https://github.com/NixOS/foundation/issues/113).
You seem to be using the old link in your repository, which is why we send you this PR.
If you feel like this is not correct or have any questions, feel free to [get in touch with us](https://github.com/NixOS/nixos-wiki-infra/issues/105).
Have a great day,
-- The NixOS Wiki-Team ❄️
=> Update NixOS Wiki link

CMakeLists.txt, examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/lines2words/lines2words1.yaml, examples/wordCount/lines2words/lines2words2.yaml, examples/wordCount/wordcount/wordcount.cpp, examples/wordCount/wordcount/wordcount.yaml, flake.lock, flake.nix, include/iceflow/consumer.hpp, include/iceflow/node-instance-service.hpp, include/iceflow/scaler.hpp, proto/iceflow.proto, src/consumer.cpp, src/node-instance-service.cpp, src/scaler.cpp
This PR implements an initial mechanism for triggering a repartitioning of an `IceflowConsumer` via gRPC (using, for instance, a Unix socket for exchanging messages with a gRPC client) using a new `IceflowScaler` class and a `NodeInstanceService` for the gRPC server it contains. The gRPC code is automatically generated at compile-time using the `protobuf_generate` function in the top-level `CMakeLists.txt`.
While implementing the scaling functionality, I've noticed that certain aspects of the repartitioning mechanism within the `IceflowConsumer` class could be simplified a bit. Therefore, this PR does not only add new code, but also changes existing parts of the implementation.
=> feat: add mechanism to trigger scaling via gRPC

src/producer.cpp
As a spin-off from #79, this PR removes some unused definitions from the `producer.cpp` file that got copied over by accident.
=> refactor(producer): remove obsolete definitions in cpp file

doc/Nix-Developer-Guide.md, examples/wordCount/lines2words/lines2words.cpp, include/iceflow/ringbuffer.hpp
In the context of #79, I've noticed a couple of minor typos and whitespace issues. This PR performs some trivial cleanup.
After the merge of this PR (and #83), I will rebase #79 once again for a cleaner commit history.
=> Fix minor typos and whitespace issues

CMakeLists.txt, include/iceflow/executor.hpp, include/iceflow/node-executor-service.hpp, include/iceflow/node-instance-service.hpp, include/iceflow/producer.hpp, proto/iceflow/node-executor.proto, proto/iceflow/node-instance.proto
This PR performs a minor refactoring and splits the Protobuf definitions in separate files per service.
=> refactor: split protobuf definitions into separate files

proto/iceflow/node-instance.proto
This is a first step on the way to implementing #82 and can serve as the basis for further discussions about the message format we want to use.
This PR depends on #86 which needs to be merged first.
=> Add protobuf definitions for production and consumption stats RPCs

include/iceflow/congestion-reporter.hpp, include/iceflow/consumer.hpp, include/iceflow/node-instance-service.hpp, include/iceflow/producer.hpp, include/iceflow/scaler.hpp, proto/iceflow/node-instance.proto, src/consumer.cpp, src/producer.cpp, src/scaler.cpp, src/services/node-instance-service.cpp
This PR now finally adds the changes from #88 to the codebase, separated into mostly atomic commits. Besides the one “TODO” line, the changes should be identical, though.
=> Add implementation of production and consumption stats RPCs

include/iceflow/executor.hpp, src/executor.cpp
This adds a missing `queryEdgeStats` method to the `IceflowExecutor` class to be able to actually retrieve the stats of the defined edges of a Node Instance.
=> feat: add queryEdgeStats to executor class

CMakeLists.txt
I've noticed that so far, the header files generated by `protobuf_generate` were not installed alongside the non-generated header files when invoking `make install`. This could cause other projects depending on IceFlow to not compile.
This PR slightly adjusts the top-level `CMakeLists.txt` file in order to fix this problem.
=> fix: also install generated proto and grpc headers

include/iceflow/executor.hpp, src/executor.cpp
Trying to use the `ExternalExecutor` interface in practice, I've noticed that it is now really that well usable in practice, as it required to be passed into the `IceflowExecutor` as a shared pointer. To simply things here, this PR replaces the function and the corresponding constructor parameter with a callback function that can be used to handle received congestion reports, which _should_ make things a bit easier to handle, at least for now.
In order to achieve the most elegant and robust solution, we should revisit the relationship of the different classes and the potential interfaces that we need to define later, once we have everything running.
=> feat!(executor): replace ExternalExecutor interface with callback

.gitignore
Noticed that the versioned `.so` files that are being generated under Linux (probably since the merge of #94) are currently not properly ignored. This simple PR changes that.
=> chore(.gitignore): ignore versioned shared library

CMakeLists.txt
After _a lot_ of fiddling around, I've managed to find a solution to let the cross-compilation succeed again :) Therefore, this PR should resolve #85.
In order to test locally, run (for example) `nix build '.#docker-text2lines-cross.aarch64-linux' --print-out-paths`.
=> fix: fix gRPC plugin cross-compilation issues

CMakeLists.txt
Just a small fix to `CMakeLists.txt` that allows the DAG parser to actually be included.
=> Fix DAG parser header not being installed by CMake

src/dag-parser.cpp
findUpstreamEdges() accidentally created a copy of the downstream edge vectors and returned references to these vectors even though they go out of scope after the function call (causing a segfault on dereference).
=> Fix segfault in findUpstreamEdges()

dag-syntax.cddl, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
This PR adds support for a `tag` field in the application graph's `container` object.
The details might still require some additional discussion, let me know if anything should be changed :)
=> feat(dag-parser): introduce tag field in container object

dag-syntax.cddl, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
This PR will eventually add support for a flexible application configuration via the application DAG to the codebase. For now, it mostly contains adjustments to the dag parser and the CDDL definitions, which we can discuss before adjusting the rest of the implementation accordingly.
=> feat(dag-parser): add support for application configurations

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/wordcount/wordcount.cpp, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
When it comes to the DAG parser, I've noticed that the current API for finding upstream edges has a few issues, as the parameter is called `nodeName`, while it actually expects the `task` member of the respective node as input.
This PR proposes a slight API change for making the use of the method a bit more convenient by accepting a reference to the actual node in question instead of a `nodeName`, so that users don't have to worry about what kind of input the method actually expects.
=> feat(dag-parser): improve findUpstreamEdges API

include/iceflow/ringbuffer.hpp
I think I noticed a small bug in the `RingBuffer` class that caused the compilation to fail under certain circumstances. This PR should fix the issue.
=> fix(ringbuffer.hpp): access m_mutex of other RingBuffer correctly

include/iceflow/executor.hpp, include/iceflow/node-instance-service.hpp
This PR might resolve an issue we are experiencing when trying to use IceFlow as dependency in other projects.
=> fix: use quotes for including gRPC header files

.linter-suppressions, cmake/sources.cmake
At least on my machine, I am having some performance problems while developing due to the `GLOB_RECURSE` argument that has been added to the `file` function call, which is used to find `ALL_SOURCES`. This PR replaces it with a simple `GLOB` and slightly more hard-coded paths to improve the performance while reconfiguring the project.
=> chore: don't use GLOB_RECURSE to find all sources

include/iceflow/dag-parser.hpp, src/dag-parser.cpp
This PR makes the usage of the DAG a bit more flexible by adding an `applicationConfiguration` field to the edges, allowing users to provide custom, application-specific data within their graph definitions.
Depends on #113, which needs to be merged first.
=> feat(dag-parser): add applicationConfiguration field to edges

.linter-suppressions, cmake/sources.cmake
#113 did not adjust the pattern for finding all source files correctly. This PR applies a minor fix so that the `include/iceflow` directory is now covered correctly again.
=> chore(sources.cmake): use correct glob pattern for include directory

examples/wordCount/lines2words/lines2words.cpp, examples/wordCount/lines2words/start_lines2words1.sh, examples/wordCount/lines2words/start_lines2words2.sh, examples/wordCount/text2lines/text2lines.cpp, examples/wordCount/wordcount/wordcount.cpp, include/iceflow/consumer.hpp, include/iceflow/iceflow.hpp, include/iceflow/node-instance-service.hpp, include/iceflow/producer.hpp, include/iceflow/scaler.hpp, src/consumer.cpp, src/iceflow.cpp, src/producer.cpp, src/scaler.cpp, src/services/node-instance-service.cpp
This is the follow-up PR to #107, which attempts to perform an overhaul of the IceFlow API using our application DAG. This PR is still heavily WIP and gradually incorporate further changes made to #107.
=> feat!: create IceFlow nodes based on application DAG

include/iceflow/iceflow.hpp
This PR provides a small potential fix for a TODO I've just noticed in the `iceflow.hpp` class.
Since the method in question is within a header file, we sadly cannot really use the logging macros to report the error, but hopefully the change is still fine.
=> fix(iceflow.hpp): improve error handling within getApplicationParameter

dag-syntax.cddl, examples/wordCount/application-DAG.json, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
Thinking about the `payloadSize` parameter that is currently part of our DAG definition, I've noticed that it is currently not only not being used by the IceFlow implementation but also not really usable with `ndn-svs` at the moment, as the library only works with the max payload size of 8000 bytes for segmentation (see [here](https://github.com/named-data/ndn-svs/blob/1bf5c25dcc3085affae58e87e3e85d0eedee6561/ndn-svs/svspubsub.cpp#L52) and [here](https://github.com/named-data/ndn-svs/blob/1bf5c25dcc3085affae58e87e3e85d0eedee6561/ndn-svs/svspubsub.hpp#L219)), offering no API for setting the payload size manually.
This PR therefore proposes just removing the parameter from the DAG definition to make things clearer for library users. Alternatively, we can also discuss how to better utilize …
=> feat!: remove payload size from DAG definition

flake.lock, flake.nix
This updates the channel used in our nix config to the latest version.
=> chore: update nixpkgs.url to the 24.11 channel

.github/workflows/build-docker-images.yml, .github/workflows/build.yml
This PR replaces the `DeterminateSystems/magic-nix-cache` action with [`nix-community/cache-nix-action`](https://github.com/nix-community/cache-nix-action) (or our fork of it, to be more specific).
This change is required due to [changes in the GitHub caching API](https://github.com/actions/cache/discussions/1510), which are [incompatible with `magic-nix-cache`](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/).
This PR also changes the nix installer action from `DeterminateSystems/nix-installer-action` to `nixbuild/nix-quick-install-action` due to incompatibilities between the former one and `cache-nix-action` (nix-community/cache-nix-action#48)
While the upstream version of cache-nix-action is also affected by these API changes, our own fork updates the underlying GitHub …
=> refactor(ci): replace magic-nix-cache with cache-nix-action

flake.nix
This is required for situations where the standard environment needs to be adjusted, e.g., if you want to enable debug symbols using the enableDebugging function.
=> fix: allow overriding stdenv and pkgs for the iceflow nix package

CMakeLists.txt
This PR fixes an issue that prevented IceFlow from being usable as a dependency after the addition of the `stats.hpp` file in #124.
=> fix(CMakeLists.txt): install `stats.hpp` file

.github/workflows/build-docker-images.yml, flake.nix, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
Adds an `envs` field to container DAG fields that allows setting container environment variables.
Also tries to fix issues with the docker container missing libgcc?
=> Allow setting container environment variables (maybe) fix docker images missing libgcc

flake.nix, include/iceflow/dag-parser.hpp, src/dag-parser.cpp
Had some issues with the previous way that the `envs` field was being parsed.
Also the node list is now passed by value (and moved) to the DAG parser constructor.
Lastly, the docker images now have their CMD arguments set correctly (previously, it still added the metrics file argument, which is no longer passed via the command line).
=> Fix DAG parser not properly setting the env field + docker images

src/dag-parser.cpp
Trying to use the examples locally, I noticed that they crashed at runtime, as the example DAG does neither provide an `envs` or `mounts` field at the moment. This PR resolves the issue by defaulting to an empty JSON object if there is no value present.
=> fix(dag-parser): use an empty object as default for envs and mounts

include/iceflow/executor.hpp, include/iceflow/scaler.hpp, src/executor.cpp, src/scaler.cpp, src/services/node-instance-service.cpp
This PR fixes some smaller issues I noticed while working on the node executor:
- Added an error message if a GRPC error occurs in the executor.
- Fixed a segfault in the scaler.
- Fixed the `partitions` variable used for rescaling being set to a wrong value.
- Allow starting gRPC server and client on the executor-side separately, enable `wait_for_ready` for executor-side requests.
- These changes were both necessary so that the executor can properly wait for the instance to come up before sending requests. Without them, the executor would just try to connect immediately after starting the server, which will fail if the client is not up yet (or the client crashed because it itself could not connect to the executor).
=> Various smaller fixes in executor and scaler

CMakeLists.txt, flake.nix
With the recent changes to the wordcount examples, compiling them with gRPC support enabled causes them to not run properly anymore in some instances. To eliminate this source of confusion (at least for me), this PR proposes changing the CMakeLists.txt file to not enable gRPC support by default anymore.
=> chore: disable gRPC support by default

flake.lock, flake.nix, include/iceflow/producer.hpp, src/consumer.cpp, src/iceflow.cpp, src/producer.cpp
After much more time than expected, this PR now contains an initial implementation of the promised backchannel deletion feature to the library. For now, I've implemented this by using a second/different kind topic with a "backchannel" suffix, which can be used to report the sequence numbers that have been processed back to the producer. Currently, the sequence numbers are serialized as JSON, which should probably be replaced/refactored.
Unfortunately, there is currently not a real good way to prevent data from being added to the store, so the sequence numbers that are reported back will now gradually fill up the data store instead (in most cases, that will probably take up less space than the regular data, but still, not really ideal). So we should probably revisit the way we handle this …
=> Add initial backchannel implementation

include/iceflow/dag-parser.hpp, src/dag-parser.cpp
When it comes to restarting the node executor, I've noticed that it could be handy to be able to instantiate a `DAGParser` from a JSON object instead of passing a file name. This PR adds a static method to the class to do just that and lets the `parseFromFile` method reuse it after reading in the specified file.
=> feat(dag-parser): allow for instantiation from a JSON object

include/iceflow/dag-parser.hpp, src/dag-parser.cpp
In #135, I made a small mistake by including an unneeded `filename` parameter in the newly added `fromJson` method. This simple PR solves the issue.
=> fix(dag-parser): remove unused filename parameter from fromJson
